### PR TITLE
Allow raytraceable entities to remove item parts from raytraces.

### PR DESCRIPTION
**Pull request by Phylogeny**
One last change I thought of was to allow raytraceable entities to prevent item parts from being considered in raytraces. Perhaps an item part is only visible under certain conditions, for instance. Raytraceable entities already have control over which interaction boxes are considered, so now they have total control over everything being considered.

I also inverted the arguments that I mentioned screwing up earlier and cleaned up the last of the explicit references I always add when creating objects for no good reason...

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Oof. Just pushed a patch to the Moped to make the chest work. You'll have to resolve the conflicts, sorry.

**Comment by Phylogeny** [comment]
No prob. :smile:

**Comment by Phylogeny** [comment]
Oops. Also, just change `CHEST_BOX` to `CHEST_BOX.getBox()` on line 206 of `EntityMoped`.

**Comment by MrCrayfish** [comment]
See latest commit.. oof 😂

**Comment by Phylogeny** [comment]
Nice. :laughing:

**Comment by Phylogeny** [comment]
That working moped chest, though... So good.

**Pull request merged**
