### PR TITLE
Fixes CUBG vehicle interaction bug.

### PR DESCRIPTION
**Pull request by Phylogeny**
At least with this PR, interacting with vehicles in CUBG won't be truly broken (you'll just have to do so normally by clicking their hitboxes). Plus, this change is a general reliability increase, in a addition to being a workaround.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I would class this as a temporary fix for now as I would still love to implement the ability to pick your seat on the golf cart. Did you find any reason to as why it the problem occurred? Is it just SpongeForge as that is what is running for CUBG?

**Comment by Phylogeny** [comment]
It's very odd. When I was testing on a CUBG server, vehicles could not be ridden unless looking at their bounding boxes and not at their parts, since the click was canceled and the server then failed.

But even more odd is that attacking vehicles failed when looking at parts and not looking at the bounding box, yet somehow still worked when looking at both the bounding box and the parts... as if the raytrace didn't cancel the click somehow. In any event, that means it's not just `mc.playerController.interactWithEntity` that fails.

Since then, I've made a temporary build of the mod that sends some client debug chat messages, and I'd like to do more testing on a CUBG server with it.

**Comment by Phylogeny** [comment]
And yes, I agree that this PR is a temporary fix for this problem, although the code in this PR should be added regardless, since it just generally means that if the raytracer ever fails, for what ever reason, it won't break things by preventing normal MC entity functionality.

**Comment by Phylogeny** [comment]
The fix is now permanent. Interaction works as intended.

**Pull request merged**
