### PR TITLE
Perform raytracing on the rendered item-parts of vehicles to allow custom/part-specific interactions.

### PR DESCRIPTION
**Pull request by Phylogeny**
I mentioned in your live stream that I'd look into this, so here it is:

As for the raytrace, it turns out that a custom intersection method for rotated bounding boxes isn't necessary. All that is necessary is to:
1. rotate the eye/focus vectors used in the raytrace around the entity (in the opposite direction)
2. rotate the resulting hit vector around the entity (in the same direction)
3. save the distance from the un-rotated hit vector to the rotated eye vector for later comparison

To ensure that the chest is usable even when the player isn't looking at the moped's bounding box (and thus isn't actually looking at the moped, as far as MC is concerned), a raytrace is performed on all mopeds in a box around the player with a semi-diameter of the player's reach distance whenever the player right-clicks. If the point the player is actually looking at is a moped chest, and if either MC knows the player is look at that same moped or if that focal point is closer to the player's eyes than the focal point MC thinks, then the click is canceled and chest is accessed.

The real tedious part is identifying the bounding box for the chest and for all the solid parts of the moped that might obscure the player's view of the chest. Most of the workflow was as follows:
1. modify a copied version of the moped_body json with your model creator to only include axis-aligned boxes that also encompass any rotated ones.
2. use a python script I wrote for scaling/rotating json files that are output by your creator to scale the json elements by the scale you use in-code
3. use another script to convert the elements of such json output files into an array of AxisAlignedBBs
4. open MC and approximate how much the boxes need to be translated, then do so with the above mentioned script
5. repeat steps 3 & 4 until the position is close enough to perfect

The end result is that chests are accessible upon right-click, although you should still allow them to be accessed while on the moped (like horses are accessed). Also, while entity bounding box rendering is turned on, the effective bounding boxes used in the raytrace render on mopeds that have chests on them.

### CODE REVIEW

**Comment by Phylogeny** [comment]
I've just generalized all this, such that EntityMoped stores the boxes and extends a custom interface. Any other entity can now do the same with <i>extremely</i> minimal code duplication. Multiple interactive boxes are also supported.

If you would like me to add (or if you would like to add, yourself) similar interactivity to other vehicles in the future, just let me know, and I'll add the above mentioned changes immediately.

**Comment by Phylogeny** [comment]
I just pushed the above mentioned changes. I doubt you will, but let me know if you want them reverted.

**Comment by Phylogeny** [comment]
Alright, don't accept this PR just yet. I've been looking into dynamically generating the boxes, like you mentioned in your last stream. I've gotten to the point of generating AxisAlignedBBs at runtime from the json files of the items you use for rendering vehicles, but dealing with rotations are going to be more difficult; not only are individual boxes rotated in each model, but entire models are having lists of GL operation applied to them.

I'll look into the possibility of pre-generating transformation matrices for each box that can be applied to the eye/focus raytrace vectors.

**Comment by Phylogeny** [comment]
I should also add that, for efficiency, each part's matrix is only settup once in init (the matrix is applied to the trangles' vertices there, as well), and that each matrix only mirrors static/hard-coded GL operations. Since the ratrace only accounts for entity rotation yaw, it's only completely accurate for stationary vehicles and for most vehicles moving in a straight line. 

If you want things like buttons/switches/levers etc. (a horn button, for example) added to the interiors of any vehicles, I can add the ability to settup those parts' matrices during every raytrace, such that dynamic GL operations are mirrored as well as static ones. Each matrix and its inverse would then be applied to the eye/forward vectors and the hit vector to get a perfect raytrace. Then, if that dynamic raytrace yields a hit and the right-click is cancelled, the static raytrace will not be performed.

**Comment by Phylogeny** [comment]
I believe this latest change I made is the is the last major one. This PR is good to go.

**Comment by Phylogeny** [comment]
I had done some last minute tweaking to a method, and ended up changes the parameter order, but didn't change the argument order passed to it. It's fixed now.

**Comment by Phylogeny** [comment]
Hmm. The changes I pushed to my branch are no longer applying to this PR, since you branched off from master...  Any idea how to fix that?

**Comment by Phylogeny** [comment]
I just tried changing the base of this PR to another branch, but GitHub just sends me to an error page. Looks like this might be a GitHub bug.

**Comment by MrCrayfish** [comment]
My guess is that your fork doesn't have the raytrace_system branch. I just didn't want to push to the master right now. Maybe try updating your fork with the new branch?

**Comment by Phylogeny** [comment]
Sadly, I just added raytrace_system to my fork and then pushed a formatting change as a test, but no dice.

**Comment by Phylogeny** [comment]
For what it's worth the fix was simply to change `direction, eyes` to `eyes, direction` on lines 793 and 803. That's all it takes to make this PR work.

**Comment by MrCrayfish** [comment]
Before I do that, I can try quickly changing the branch back to master to see if the commits can be added.

**Comment by Phylogeny** [comment]
Sure.

**Comment by MrCrayfish** [comment]
Welp, that didn't work. I'll go ahead a merge the changes.

**Comment by MrCrayfish** [comment]
I can do it, it's all good. Definitely going to take advantage of this system and already have a ton of ideas 😊 Thank you so much. Did you happen to add yourself to the credits? If not, I will put you in there.

**Comment by Phylogeny** [comment]
No, I haven't. Whatever's good. :grin:
And yeah, the sky's the limit with this system. I've never seen a mod does anything like a legitimate raytrace on the actual visible parts of an entity - its always a very rough approximation.

**Comment by Phylogeny** [comment]
Also, I'll stand by this system; if there are any issues with it that need fixing, limitations that need overcoming, or just functionality you decide you want changed in the future, I'll handle them as they come.

**Pull request merged**
